pipeline {
  agent { label 'v-collab-stg' }
  options {
    timestamps()
  }
  stages {
    stage('Deloy Stg') {
      when {
        beforeOptions true
        anyOf {
          environment name: 'gitlabBranch', value: 'stg'
        }
      }
      steps {
        gitlabCommitStatus('Deloy Stg') {
          sh 'sudo -u zulip /home/zulip/ide-ext/deploy/deploy.sh'
        }
      }
    }
  }
}
